### PR TITLE
Add renovate to notify about new dependency versions

### PR DESCRIPTION
**Pull request by kimdre**
This PR adds a renovate config that notifies about new versions for dependencies such as friendly-widget (friendlycaptcha).

With renovate enabled for this repo, the renovate bot will scrape the files in this repo for dependencies and will automatically search for new versions for those.

If new versions are found, renovate will create pull requests for those:
image

A dashboard issue will also give you a a overview about all detected dependencies:
image

To install renovate on github see the onboarding docs: https://github.com/renovatebot/renovate/blob/main/docs/usage/getting-started/installing-onboarding.md

### CODE REVIEW

**Comment by kimdre** [comment]
@christianwgd Thank you for merging! :) Don't forget to enable the renovate bot in your account: https://github.com/renovatebot/renovate/blob/main/docs/usage/getting-started/installing-onboarding.md

**Comment by christianwgd** [comment]
I'm 100% sure what I'm getting here. Dependency notification in general is not a bad idea. Does renovate provide this service for free? I'm not aware of the conditions since their website mend.io is telling very big numbers.
Anyway, just got that first dependency alert...

**Comment by kimdre** [comment]
Yes they provide it for free.

**Comment by christianwgd** [comment]
Thanks, looks like it's working, just published a new release with updated javascript and new version of actions.

**Pull request merged**
